#!/bin/bash

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/boris-magrini_confronting_the_machine.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/boris_magrini/boris-magrini_confronting_the_machine_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/boris-magrini_confronting_the_machine_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/bruno_latour-visualization_and_cognition_drawing_things_together.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/bruno_latour/bruno_latour-visualization_and_cognition_drawing_things_together_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/bruno_latour-visualization_and_cognition_drawing_things_together_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/bruno_latour-we_have_never_been_modern.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/bruno_latour/bruno_latour-we_have_never_been_modern_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/bruno_latour-we_have_never_been_modern_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/bruno_latour-why_has_critique_run_out_of_steam.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/bruno_latour/bruno_latour-why_has_critique_run_out_of_steam_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/bruno_latour-why_has_critique_run_out_of_steam_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/buckminster_fuller-everything_i_know.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/buckminster_fuller/buckminster_fuller-everything_i_know_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/buckminster_fuller-everything_i_know_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/cae-recombinant_theater.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/cae/cae-recombinant_theater_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/cae-recombinant_theater_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/dieter_daniels-audiovisuology.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/dieter_daniels/dieter_daniels-audiovisuology_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/dieter_daniels-audiovisuology_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/dough_engelbart-the_mouse_and_the_desktop.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/dough_engelbart/dough_engelbart-the_mouse_and_the_desktop_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/dough_engelbart-the_mouse_and_the_desktop_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/eric_tamm-brian_eno_his_music_and_the_vertical_color_of_sound.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/eric_tamm/eric_tamm-brian_eno_his_music_and_the_vertical_color_of_sound_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/eric_tamm-brian_eno_his_music_and_the_vertical_color_of_sound_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/erkki_huhtamo_jussi_parikka-media_archaeology_approaches_applications_and_implications.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/erkki_huhtamo_jussi_parikka/erkki_huhtamo_jussi_parikka-media_archaeology_approaches_applications_and_implications_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/erkki_huhtamo_jussi_parikka-media_archaeology_approaches_applications_and_implications_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/espen_aarseth-cybertext_perspectives_on_ergodic_literature.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/espen_aarseth/espen_aarseth-cybertext_perspectives_on_ergodic_literature_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/espen_aarseth-cybertext_perspectives_on_ergodic_literature_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/eugene_thacker-darklife_negotiation_nothingness_and_the_will_to_live_in_schopenhauer.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/eugene_thacker/eugene_thacker-darklife_negotiation_nothingness_and_the_will_to_live_in_schopenhauer_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/eugene_thacker-darklife_negotiation_nothingness_and_the_will_to_live_in_schopenhauer_i03e10s2.log
