#!/bin/bash

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/kazys_varnelis-the_rise_of_network_culture.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/kazys_varnelis/kazys_varnelis-the_rise_of_network_culture_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/kazys_varnelis-the_rise_of_network_culture_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/frieder_nake-paragraphs_on_computer_art_past_and_present.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/frieder_nake/frieder_nake-paragraphs_on_computer_art_past_and_present_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/frieder_nake-paragraphs_on_computer_art_past_and_present_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/richard_barbrook_andy_cameron-the_internet_revolution_from_dotcom_capitalism_to_cybernetic_communism.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/richard_barbrook_andy_cameron/richard_barbrook_andy_cameron-the_internet_revolution_from_dotcom_capitalism_to_cybernetic_communism_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/richard_barbrook_andy_cameron-the_internet_revolution_from_dotcom_capitalism_to_cybernetic_communism_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/frieder_nake-behind_the_canvas_an_algorithmic_space.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/frieder_nake/frieder_nake-behind_the_canvas_an_algorithmic_space_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/frieder_nake-behind_the_canvas_an_algorithmic_space_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/marion_hamm-indymedia_concatenations_of_physical_and_virtual_space.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/marion_hamm/marion_hamm-indymedia_concatenations_of_physical_and_virtual_space_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/marion_hamm-indymedia_concatenations_of_physical_and_virtual_space_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/matteo_pasquinelli-radical_machines_against_the_techno_empire.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/matteo_pasquinelli/matteo_pasquinelli-radical_machines_against_the_techno_empire_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/matteo_pasquinelli-radical_machines_against_the_techno_empire_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/matt_pearson-novelty_waves.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/matt_pearson/matt_pearson-novelty_waves_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/matt_pearson-novelty_waves_i03e10s2.log

KERAS_BACKEND=tensorflow python keras_lstm/lstm_train.py --input /mnt/drive1/data/eco/pdf_to_text_postprocessed/neal_stephenson-in_the_beginning_was_the_command_line.txt --iterations 3 --epochs 10 --steps 2 --model_save_path /home/marcel/projects/eco/src/python/keras_lstm/models/neal_stephenson/neal_stephenson-in_the_beginning_was_the_command_line_i03e10s2.h5 --save_every 1 >> keras_lstm/logs/neal_stephenson-in_the_beginning_was_the_command_line_i03e10s2.log